apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ow0xwbpfe-python 
  janus-idp.io/tekton: ow0xwbpfe-python
  backstage.io/kubernetes-id: ow0xwbpfe-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ow0xwbpfe-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml