apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ow0xwbpfe-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ow0xwbpfe-python 
  name: ow0xwbpfe-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ow0xwbpfe-python 
